import type { Job, Message } from './types'

export const mockJobs: Job[] = [
  {
    id: '1',
    company: 'Apex Solutions',
    companyColor: '#dbeafe',
    companyInitials: 'AS',
    verified: true,
    matchPercent: 93,
    title: 'Marketing Manager',
    location: 'Lagos Island',
    salary: '₦250K – ₦350K',
    jobType: 'Full-time',
    experience: '7 years',
    tags: ['Lagos', '7 Yrs exp', '₦250K–350K', 'Full-time'],
    description:
      'We are seeking an experienced and results-oriented Marketing Manager to lead brand strategy and growth across multiple channels. You will develop and execute comprehensive marketing strategies that strengthen brand visibility, generate qualified leads, and drive revenue growth across Nigeria and West Africa.',
    requirements: [
      '7+ years of marketing experience in a leadership role',
      'Proven track record in brand management and growth',
      'Strong command of digital marketing tools and analytics',
      'Experience managing cross-functional teams',
      'BSc in Marketing, Business Administration, or related field',
    ],
    aboutCompany:
      'Apex Solutions is a leading pan-African business consultancy helping companies scale across Nigeria, Ghana, and Kenya. Founded in 2012, we serve 500+ enterprise clients and pride ourselves on driving sustainable business growth.',
    postedAt: '2 days ago',
    applicants: 34,
  },
  {
    id: '2',
    company: 'Horizon Tech',
    companyColor: '#ede9fe',
    companyInitials: 'HT',
    verified: true,
    matchPercent: 88,
    title: 'Product Designer',
    location: 'Abuja',
    salary: '₦180K – ₦240K',
    jobType: 'Full-time',
    experience: '4 years',
    tags: ['Abuja', '4 Yrs exp', '₦180K–240K', 'Full-time'],
    description:
      'Join our growing product team as a Product Designer. You will own the end-to-end design process from discovery and ideation to high-fidelity prototypes and developer handoff. You\'ll collaborate closely with engineering and product leadership to shape our next generation of financial products.',
    requirements: [
      '4+ years as a product or UX designer',
      'Mastery of Figma and building scalable design systems',
      'Experience conducting user research and usability testing',
      'Strong portfolio showcasing mobile and web product work',
      'Excellent communication and collaboration skills',
    ],
    aboutCompany:
      'Horizon Tech builds software solutions for the financial services industry across West Africa. Our flagship products serve over 2 million users and we\'re growing fast.',
    postedAt: '1 day ago',
    applicants: 51,
  },
  {
    id: '3',
    company: 'NovaPay',
    companyColor: '#ccfbf1',
    companyInitials: 'NP',
    verified: false,
    matchPercent: 79,
    title: 'Sales Executive',
    location: 'Lagos',
    salary: '₦100K – ₦150K',
    jobType: 'Full-time',
    experience: '2 years',
    tags: ['Lagos', '2 Yrs exp', '₦100K–150K', 'Full-time'],
    description:
      'We are looking for a motivated Sales Executive to drive new business acquisition. Your role involves prospecting, qualifying leads, delivering compelling product demos, and closing deals with SME and enterprise clients across Lagos.',
    requirements: [
      '2+ years in B2B or fintech sales',
      'Proven ability to meet and exceed monthly targets',
      'Excellent communication and negotiation skills',
      'Comfortable working in a fast-paced startup environment',
      'Familiarity with CRM tools (HubSpot, Pipedrive)',
    ],
    aboutCompany:
      'NovaPay is a fast-growing payments fintech enabling seamless money movement for businesses and individuals across Africa. We process over ₦10B in transactions monthly.',
    postedAt: '3 days ago',
    applicants: 27,
  },
  {
    id: '4',
    company: 'Greenfin Bank',
    companyColor: '#dcfce7',
    companyInitials: 'GB',
    verified: true,
    matchPercent: 91,
    title: 'Software Engineer',
    location: 'Remote',
    salary: '₦300K – ₦450K',
    jobType: 'Remote',
    experience: '5 years',
    tags: ['Remote', '5 Yrs exp', '₦300K–450K', 'Remote'],
    description:
      'As a Software Engineer at Greenfin you will build and scale the core banking platform serving millions of customers. You\'ll work on high-impact systems including real-time payments, lending infrastructure, and identity — at a scale few engineers in Nigeria get to experience.',
    requirements: [
      '5+ years of software engineering experience',
      'Strong proficiency in TypeScript, Node.js or Go',
      'Experience designing and operating distributed systems',
      'Solid understanding of SQL and NoSQL databases',
      'Knowledge of financial systems and PCI compliance is a plus',
    ],
    aboutCompany:
      'Greenfin Bank is a digital-first bank serving 3M+ customers in Nigeria. We are on a mission to democratize access to world-class financial services for every African.',
    postedAt: '5 hours ago',
    applicants: 18,
  },
  {
    id: '5',
    company: 'ClearPath HR',
    companyColor: '#fef3c7',
    companyInitials: 'CP',
    verified: true,
    matchPercent: 85,
    title: 'Talent Acquisition Lead',
    location: 'Lagos',
    salary: '₦200K – ₦280K',
    jobType: 'Hybrid',
    experience: '6 years',
    tags: ['Lagos', '6 Yrs exp', '₦200K–280K', 'Hybrid'],
    description:
      'ClearPath is looking for a Talent Acquisition Lead to own our end-to-end hiring process. You will partner with hiring managers across the business to attract and close top-tier talent — from engineers and designers to sales and operations.',
    requirements: [
      '6+ years in talent acquisition or human resources',
      'Experience building and optimising hiring pipelines',
      'Strong knowledge of employer branding strategies',
      'Excellent interpersonal and organisational skills',
      'Familiarity with ATS platforms (Lever, Greenhouse)',
    ],
    aboutCompany:
      'ClearPath HR is Nigeria\'s leading human capital solutions provider, working with 200+ companies across tech, finance, and FMCG to build world-class teams.',
    postedAt: '1 week ago',
    applicants: 43,
  },
  {
    id: '6',
    company: 'LagosAI',
    companyColor: '#fce7f3',
    companyInitials: 'LA',
    verified: true,
    matchPercent: 87,
    title: 'AI/ML Engineer',
    location: 'Lagos',
    salary: '₦400K – ₦600K',
    jobType: 'Full-time',
    experience: '4 years',
    tags: ['Lagos', '4 Yrs exp', '₦400K–600K', 'Full-time'],
    description:
      'Join LagosAI as an AI/ML Engineer to build cutting-edge machine learning systems that power our recommendation and matching engines. You will research, train, evaluate, and deploy models that directly improve outcomes for millions of users.',
    requirements: [
      '4+ years in machine learning or AI engineering',
      'Proficiency in Python, PyTorch or TensorFlow',
      'Hands-on experience deploying ML models to production',
      'Strong grounding in statistics and data modelling',
      "MSc in Computer Science or related field preferred",
    ],
    aboutCompany:
      'LagosAI is at the forefront of artificial intelligence adoption in Africa, building intelligent systems for recruitment, finance, and healthcare. Backed by leading global investors.',
    postedAt: '3 days ago',
    applicants: 12,
  },
]

export const mockMessages: Message[] = [
  {
    id: '1',
    company: 'Apex Solutions',
    companyColor: '#dbeafe',
    companyInitials: 'AS',
    role: 'Marketing Manager',
    lastMessage: 'We reviewed your profile and would love to schedule an interview.',
    time: '10:24',
    unread: 2,
    isOnline: true,
  },
  {
    id: '2',
    company: 'Greenfin Bank',
    companyColor: '#dcfce7',
    companyInitials: 'GB',
    role: 'Software Engineer',
    lastMessage: 'Thanks for applying! Could you share a link to your portfolio?',
    time: 'Yesterday',
    unread: 1,
    isOnline: false,
  },
  {
    id: '3',
    company: 'Horizon Tech',
    companyColor: '#ede9fe',
    companyInitials: 'HT',
    role: 'Product Designer',
    lastMessage: 'Your skills are a great match. When are you available to chat?',
    time: 'Mon',
    unread: 0,
    isOnline: true,
  },
  {
    id: '4',
    company: 'ClearPath HR',
    companyColor: '#fef3c7',
    companyInitials: 'CP',
    role: 'Talent Acquisition Lead',
    lastMessage: 'Application received! We will be in touch within 3 business days.',
    time: 'Mon',
    unread: 0,
    isOnline: false,
  },
  {
    id: '5',
    company: 'LagosAI',
    companyColor: '#fce7f3',
    companyInitials: 'LA',
    role: 'AI/ML Engineer',
    lastMessage: 'Exciting opportunity — your background is exactly what we need!',
    time: 'Sun',
    unread: 3,
    isOnline: true,
  },
]
