import type { Job, Match } from './types'

export const mockJobs: Job[] = [
  {
    id: '1',
    company: 'Seepco Nigeria',
    title: 'Sales Assistant',
    location: 'Lagos Island · On-site',
    salary: '₦250,000 – ₦350,000/month',
    type: 'Full-time',
    posted: '2 days ago',
    verified: true,
    description: 'We are looking for a motivated Sales Assistant to join our team and help drive revenue growth across our Lagos territory. You will work closely with the commercial team to develop new opportunities.',
    requirements: ['2+ years sales experience', 'Strong communication skills', 'CRM proficiency', 'Lagos-based'],
    niceToHave: ['FMCG experience', 'Salesforce certification'],
    about: 'Seepco is a leading Nigerian energy company with operations across the country, committed to powering homes and businesses.',
    logoColor: '#0f65ef',
    logoInitial: 'S',
  },
  {
    id: '2',
    company: 'TechBridge Ltd',
    title: 'Business Development Exec',
    location: 'Victoria Island · Hybrid',
    salary: '₦300,000 – ₦400,000/month',
    type: 'Full-time',
    posted: '1 day ago',
    verified: true,
    description: 'Drive new business partnerships and revenue streams for a fast-growing tech company expanding across West Africa.',
    requirements: ['3+ years BD experience', 'Tech sector knowledge', 'Strong network'],
    niceToHave: ['MBA', 'SaaS experience'],
    about: 'TechBridge connects African businesses with global technology solutions, bridging the innovation gap.',
    logoColor: '#6030e0',
    logoInitial: 'T',
  },
  {
    id: '3',
    company: 'NovaBanc',
    title: 'Relationship Manager',
    location: 'Ikeja · On-site',
    salary: '₦280,000 – ₦360,000/month',
    type: 'Full-time',
    posted: '3 days ago',
    verified: true,
    description: 'Manage and grow a portfolio of retail and SME banking clients, providing tailored financial solutions.',
    requirements: ['Banking experience preferred', 'Customer relationship skills', 'Finance background'],
    niceToHave: ['CIBN certification', 'Portfolio management experience'],
    about: 'NovaBanc is a digital-first bank serving millions of Nigerians with innovative financial products.',
    logoColor: '#e06020',
    logoInitial: 'N',
  },
  {
    id: '4',
    company: 'Apex Solutions',
    title: 'Marketing Manager',
    location: 'Lekki · Hybrid',
    salary: '₦350,000 – ₦500,000/month',
    type: 'Full-time',
    posted: '5 hours ago',
    verified: true,
    description: 'Lead our marketing strategy across digital and traditional channels to drive brand awareness and customer acquisition.',
    requirements: ['5+ years marketing experience', 'Digital marketing expertise', 'Team leadership'],
    niceToHave: ['FMCG background', 'Google Ads certification'],
    about: 'Apex Solutions is a leading management consulting firm helping Nigerian businesses scale effectively.',
    logoColor: '#20b06e',
    logoInitial: 'A',
  },
  {
    id: '5',
    company: 'Greenfin Bank',
    title: 'Software Engineer',
    location: 'Remote · Nigeria',
    salary: '₦400,000 – ₦600,000/month',
    type: 'Full-time',
    posted: '1 day ago',
    verified: true,
    description: 'Build and scale the core banking platform serving millions of customers across Nigeria and West Africa.',
    requirements: ['5+ years engineering experience', 'Node.js or Python', 'Distributed systems knowledge'],
    niceToHave: ['Fintech experience', 'AWS certifications'],
    about: 'Greenfin is a next-generation digital bank built for the African market, processing millions in daily transactions.',
    logoColor: '#1aa34a',
    logoInitial: 'G',
  },
]

export const mockMatches: Match[] = [
  {
    id: 'm1',
    company: 'Seepco Nigeria',
    jobTitle: 'Sales Assistant',
    logoColor: '#0f65ef',
    logoInitial: 'S',
    lastMessage: "Hi! I'm Tunde from Seepco. I reviewed your profile and would love to chat.",
    timestamp: '2h ago',
    unread: 1,
    matchedDate: 'Monday, 25 Aug',
  },
  {
    id: 'm2',
    company: 'TechBridge Ltd',
    jobTitle: 'Business Development Exec',
    logoColor: '#6030e0',
    logoInitial: 'T',
    lastMessage: 'Thanks for your interest! Can we schedule a quick call?',
    timestamp: 'Yesterday',
    unread: 0,
    matchedDate: 'Sunday, 24 Aug',
  },
]

export const mockApplications = [
  { id: 'a1', company: 'Seepco Nigeria', title: 'Sales Assistant', logoColor: '#0f65ef', logoInitial: 'S', status: 'matched', date: '2 days ago' },
  { id: 'a2', company: 'TechBridge Ltd', title: 'Business Dev Exec', logoColor: '#6030e0', logoInitial: 'T', status: 'viewed', date: '1 day ago' },
  { id: 'a3', company: 'NovaBanc', title: 'Relationship Manager', logoColor: '#e06020', logoInitial: 'N', status: 'waiting', date: '3 days ago' },
  { id: 'a4', company: 'Apex Solutions', title: 'Marketing Manager', logoColor: '#20b06e', logoInitial: 'A', status: 'interview', date: '4 days ago' },
  { id: 'a5', company: 'Greenfin Bank', title: 'Software Engineer', logoColor: '#1aa34a', logoInitial: 'G', status: 'not-selected', date: '5 days ago' },
]
